# Generated by Django 5.1.11 on 2025-08-14 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def update_collation(apps, schema_editor):
    print('Database vendor: {}'.format(schema_editor.connection.vendor))
    if not schema_editor.connection.vendor.startswith('mysql'):
        return
    schema_editor.execute('ALTER TABLE dojo_snyk_issue CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin')


def rollback_collation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0242_file_upload_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snyk_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Snyk issue key', max_length=60, unique=True)),
                ('status', models.CharField(help_text='Snyk issue status', max_length=20)),
                ('type', models.CharField(help_text='Snyk issue type', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Snyk_Issue_Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finding_status', models.CharField(max_length=100)),
                ('snyk_status', models.CharField(max_length=50)),
                ('transitions', models.CharField(max_length=100)),
                ('snyk_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.Snyk_Issue')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='snyk_issue',
            field=models.ForeignKey(blank=True, help_text='Snyk issue', null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Snyk_Issue'),
        ),
        migrations.RunPython(update_collation, rollback_collation, atomic=False),
    ]